stages:
  - publish
  - deliver
  - deploy

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

fetch-loop:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "tweetmetric-fetch-loop" "2.4"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - src/*
      - ci/docker-deliver.sh
      - docker-compose.yml
      - Dockerfile
  tags:
    - tweetmetric

viz-server:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "tweetmetric-viz-server" "2.4"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - src/*
      - ci/docker-deliver.sh
      - docker-compose.yml
      - Dockerfile
  tags:
    - tweetmetric

deploy:
  stage: deploy
  script:
    - setsid ./ci/deploy.sh
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - src/*
      - ci/deploy.sh
      - docker-compose.yml
      - Dockerfile
  tags:
    - tweetmetric
